{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "landing.fullname" . }}
  labels:
    {{- include "landing.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-{{ .Values.service.targetport | default .Values.service.port }}
  selector:
    {{- include "landing.selectorLabels" . | nindent 4 }}
{{- end }}
