apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-signer.fullname" . }}-config
  labels:
    {{- include "api-signer.labels" . | nindent 4 }}
data:
  config: |
    {"Host":"{{ .Values.apiSignerConfig.host }}","NumThreads": {{ .Values.apiSignerConfig.numThreads }}}
