{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
    {{- with .Values.secretManager.secrets }}
    {{- range . }}
        - objectName: "{{ . }}"
          objectType: "secretsmanager"
    {{- end }}
    {{- end }}
{{- end }}
