{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
    {{- if .targetPort }}
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- if .protocol }}
      protocol: {{ .protocol }}
    {{- else }}
      protocol: TCP
    {{- end }}
  {{- end }}
  selector:
    {{- include "main.selectorLabels" . | nindent 4 }}
{{- end }}