{{- if .Values.node.ingress.enabled }}
{{- if .Values.node.grpc.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
  labels:
  {{- include "node.labels" . | nindent 4}}
  annotations:
    konghq.com/protocols: "grpcs"
  {{- with .Values.node.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
    {{- if .Values.node.ingress.externalDNS }}
    external-dns.alpha.kubernetes.io/hostname: "grpc.{{ .Values.node.ingress.host }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.node.ingress.class }}
  rules:
    - host: grpc.{{ .Values.node.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
                port:
                  number: 9090
            path: /
            pathType: {{ .Values.node.ingress.pathType }}
  tls:
  - hosts:
    - grpc.{{ .Values.node.ingress.host }}
    secretName: {{ .Release.Name }}-{{ .Values.node.name }}-grpc-tls
{{- end }}
{{- end }}
