{{- if .Values.node.ingress.enabled }}
{{- if .Values.node.grpc.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
  labels:
  {{- include "node.labels" . | nindent 4}}
  annotations:
    konghq.com/protocols: "grpcs"
spec:
  ingressClassName: {{ .Values.node.ingress.class }}
  rules:
    - host: grpc.{{ .Release.node.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
            port:
              number: 9090
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - grpc.{{ .Values.node.ingress.host }}
      secretName: {{ .Release.Name }}-{{ .Values.node.name }}-grpc-tls
{{- end }}
{{- end }}
