---
{{- if .Values.node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-http
  labels:
    {{- include "node.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "node.serviceAnnotations" . |nindent 4}}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.node.rpc.enabled }}
    - name: rpc
      port: 26657
      targetPort: 26657
      protocol: TCP
    {{- end}}
    {{- if .Values.node.p2p.enabled }}
    - name: p2p
      port: 26656
      targetPort: 26656
      protocol: TCP
    {{- end}}
    {{- if .Values.node.api.enabled }}
    - name: api
      port: 1317
      targetPort: 1317
      protocol: TCP
    {{- end}}
    {{- if .Values.node.metrics.enabled }}
    - name: telemetry
      port: 26660
      targetPort: 26660
      protocol: TCP
    {{- end}}
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.node.grpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
  labels:
    {{- include "node.selectorLabels" . | nindent 4 }}
  annotations:
    konghq.com/protocol: grpc
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.node.enabled }}
{{- if .Values.node.p2p.external }}
{{- range $i, $e := until (int .Values.node.replicaCount)}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.name" $ }}-{{ $i }}-p2p
  labels:
    statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
  annotations:
    {{- include "p2p.serviceAnnotations" $ |nindent 4}}
    {{- if "p2p.externalDNS" }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "node.name.short" $ }}-{{ $i }}.{{ include "p2p.externalDNS.domain" $}}
    {{- end}}
spec:
  type: LoadBalancer
  ports:
    - name: p2p
      port: 26656
      targetPort: 26656
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
---
{{- end }}
{{- end }}
{{- end }}
