---
{{- if .Values.node.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}
  labels:
    {{- include "node.selectorLabels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.extraLabels }}
    {{- toYaml . |nindent 4 }} 
    {{- end }}
spec:
  jobLabel: {{ .Release.Name }}-{{ .Values.node.name }}
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: telemetry
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
{{- end}}
