---
{{- if .Values.node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-http
  labels:
    {{- include "node.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.node.rpc.enabled }}
    - name: rpc
      port: 26657
      targetPort: 26657
      protocol: TCP
    {{- end}}
    {{- if .Values.node.p2p.enabled }}
    - name: p2p
      port: 26656
      targetPort: 26656
      protocol: TCP
    {{- end}}
    {{- if .Values.node.api.enabled }}
    - name: api
      port: 1317
      targetPort: 1317
      protocol: TCP
    {{- end}}
    {{- if .Values.node.metrics.enabled }}
    - name: telemetry
      port: 26660
      targetPort: 26660
      protocol: TCP
    {{- end}}
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.node.grpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-grpc
  labels:
    {{- include "node.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
{{- end }}
