---
{{- if .Values.node.metrics.enabled }}
{{- range $i, $e := until (int .Values.node.replicaCount)}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "node.name" $ }}-{{ $i }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
    {{- include "node.selectorLabels" $ | nindent 4 }}
    {{- include "serviceMonitor.extraLabels" $ | nindent 4 }}
spec:
  jobLabel: {{ include "node.name" $ }}-{{ $i }}
  selector:
    matchLabels:
        statefulset.kubernetes.io/pod-name: {{ include "node.name" $ }}-{{ $i }}
  endpoints:
    - port: telemetry
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
---
{{- end}}
{{- end}}
