---
{{- if .Values.node.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
       {{- include "node.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- with .Values.podAnnotations }}
        annotations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        labels:
            {{- include "node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end}}
      initContainers:
        - name: init
          image: "{{ .Values.image }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
          command: [ "/bin/bash" , "/scripts/init.sh" ]
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SYNC_METHOD
              value: "{{.Values.syncMethod }}"
            - name: SNAPSHOT_URL
              value: "{{.Values.snapshot.url }}"
            {{- if .Values.scratch.genesisUrl }}
            - name: GENESIS_URL
              value: "{{ .Values.scratch.genesisUrl }}"
            {{- end}}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: {{ include "node.name" . }}-data
              mountPath: /root/.warden
        {{- if .Values.node.mnemonicSecretName }}
        - name: init-keys
          image: "{{ .Values.image }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "cat /tmp/mnemonic/MNEMONIC | wardend keys add validator --recover --keyring-backend test",
            ]
          volumeMounts:
            - name: {{ include "node.name" . }}-data
              mountPath: /root/.warden
            - name: {{ include "node.name" . }}-mnemonic
              mountPath: /tmp/mnemonic
        {{- end}}
      containers:
        - name: {{ include "node.name" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.node.ready }}
          command: ["/usr/bin/wardend","start"]
          {{- else}}
          command: ["sleep","36000"]
          {{- end}}
          ports:
            {{- if .Values.node.rpc.enabled }}
            - name: rpc
              containerPort: 26657
              protocol: TCP
            {{- end}}
            {{- if .Values.node.p2p.enabled }}
            - name: p2p
              containerPort: 26656
              protocol: TCP
            {{- end}}
            {{- if .Values.node.api.enabled }}
            - name: api
              containerPort: 1317
              protocol: TCP
            {{- end}}
            {{- if .Values.node.grpc.enabled }}
            - name: grpc
              containerPort: 9090
              protocol: TCP
            {{- end}}
            {{- if .Values.node.metrics.enabled }}
            - name: telemetry
              containerPort: 26660
              protocol: TCP
            {{- end}}
          {{- if .Values.node.ready }}
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: rpc
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: rpc
          {{- end }}
          volumeMounts:
            - name: {{ include "node.name" . }}-data
              mountPath: /root/.warden
            - name: config
              mountPath: /root/.warden/config/config.toml
              subPath: config.toml
            - name: config
              mountPath: /root/.warden/config/app.toml
              subPath: app.toml
          {{- if .Values.node.nodeKeysSecretName }}
            - name: {{ include "node.name" . }}-keys
              mountPath: /root/.warden/config/node_key.json
              subPath: node_key.json
          {{- end}}
          {{- if .Values.node.nodeKeysSecretName }}
            - name: {{ include "node.name" . }}-keys
              mountPath: /root/.warden/config/priv_validator_key.json
              subPath: priv_validator_key.json
          {{- end}}
          {{- if .Values.node.genesisSecretName }}
            - name: genesis
              mountPath: /root/.warden/config/genesis.json
              subPath: genesis.json
          {{- end}}
          {{- end}}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{.Release.Name}}-{{ .Values.node.name }}-scripts
      - name: config
        configMap:
          name: {{ .Release.Name }}-{{ .Values.node.name }}-config
      - name: {{ include "node.name" . }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.node.name }}-pvc
      {{- if .Values.node.nodeKeysSecretName }}
      - name: {{ include "node.name" . }}-keys
        secret:
          secretName: {{.Values.node.nodeKeysSecretName}}
      {{- end}}
      {{- if .Values.node.mnemonicSecretName }}
      - name: {{ include "node.name" . }}-mnemonic
        secret:
          secretName: {{.Values.node.mnemonicSecretName }}
      {{- end}}
      {{- if .Values.node.genesisSecretName }}
      - name: genesis
        secret:
          secretName: {{ .Values.node.genesisSecretName }}
      {{- end}}
