---
{{- if .Values.node.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
       {{- include "node.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- with .Values.podAnnotations }}
        annotations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        labels:
            {{- include "node.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      initContainers:
        - name: init
          image: "{{ .Values.image }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
          command: [ "/bin/ash" , "/scripts/init.sh" ]
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SYNC_METHOD
              value: "{{.Values.syncMethod }}"
            - name: HOME
              value: "/warden-data"
            - name: WARDEND_HOME
              value: "/warden-data/.warden"
            - name: SNAPSHOT_URL
              value: "{{.Values.snapshot.url }}"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: {{ include "node.name" . }}-data
              mountPath: /warden-data
      containers:
        - name: {{ include "node.name" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/usr/bin/wardend","start"]
          ports:
            {{- if .Values.node.rpc.enabled }}
            - name: rpc
              containerPort: 26657
              protocol: TCP
            {{- end}}
            {{- if .Values.node.p2p.enabled }}
            - name: p2p
              containerPort: 26656
              protocol: TCP
            {{- end}}
            {{- if .Values.node.api.enabled }}
            - name: api
              containerPort: 1317
              protocol: TCP
            {{- end}}
            {{- if .Values.node.grpc.enabled }}
            - name: grpc
              containerPort: 9090
              protocol: TCP
            {{- end}}
            {{- if .Values.node.metrics.enabled }}
            - name: telemetry
              containerPort: 26660
              protocol: TCP
            {{- end}}
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: rpc
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: rpc
          {{- end }}
          env:
            - name: HOME
              value: "/warden-data"
            - name: WARDEND_HOME
              value: "/warden-data/.warden"
          volumeMounts:
            - name: {{ include "node.name" . }}-data
              mountPath: /warden-data
            - name: config
              mountPath: /warden-data/.warden/config/config.toml
              subPath: config.toml
            - name: config
              mountPath: /warden-data/.warden/config/app.toml
              subPath: app.toml
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{.Release.Name}}-{{ .Values.node.name }}-scripts
      - name: config
        configMap:
          name: {{ .Release.Name }}-{{ .Values.node.name }}-config
      - name: {{ include "node.name" . }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.node.name }}-pvc
