{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-{{ .Values.service.targetport | default .Values.service.port }}
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
{{- end }}