---
image:
  repository: ghcr.io/warden-protocol/discord-faucet
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsGroup: 65532
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false

# env:
# envFrom: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

logLevel: info
