---
image: ghcr.io/warden-protocol/discord-faucet
imagePullPolicy: IfNotPresent
tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false

# env:
# envFrom: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

logLevel: info
