---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "faucet.fullname" . }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
    {{- if .targetPort }}
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- if .protocol }}
      protocol: {{ .protocol }}
    {{- else }}
      protocol: TCP
    {{- end }}
  {{- end }}
  selector:
    {{- include "faucet.selectorLabels" . | nindent 4 }}
