# Default values for api-signer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fordefi.jfrog.io/fordefi/api-signer
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets:
- name: fordefi-reg-creds
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

volumes:
- name: filedb
  projected:
    sources:
    - secret:
        name: api-signer-secrets
        items:
        - key: secrets
          path: SECRETS.json
        - key: credentials
          path: CREDENTIALS.json
    - configMap:
        name: api-signer-config
        items:
        - key: config
          path: CONFIG.json

volumeMounts:
- name: filedb
  mountPath: /storage/filedb
  readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

apiSignerConfig:
  host: https://api.fordefi.com
  numThreads: 1

secretManager:
  enabled: false
  serviceAccount:
    create: false
    name: ""
    annotations: {}
  secrets: []
