---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discord-faucet.fullname" . }}
  labels:
    {{- include "discord-faucet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "discord-faucet.selectorLabels" . | nindent 4 }}
