{{- if .Values.ingress.enabled }}
{{- $fullName := include "webhooks.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "webhooks.labels" . | nindent 4}}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . |nindent 4}}
  {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "webhooks.fullname" . }}
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Release.Name }}-webhooks.tls
{{- end }}
