---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "serviceAnnotations" . |nindent 4}}
spec:
  type: ClusterIP
  ports:
    - name: horcrux
      port: 2222
      targetPort: 2222
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 6001
      targetPort: 6001
      protocol: TCP
    {{- end}}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
