{{- if .Values.ingress.enabled }}
{{- $fullName := include "wardenkms.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "wardenkms.labels" . | nindent 4}}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . |nindent 4}}
  {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className | quote }}
  rules:
  {{- with .Values.ingress.rules }}
  {{-  toYaml . | nindent 6 }}
  {{- end }}
  tls:
  {{- with .Values.ingress.tls }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}