{{- if .Values.secretmanager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "wardenkms.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
    {{- with .Values.secretmanager.secrets }}
    {{- range . }}
        - objectName: "{{ . }}"
          objectType: "secretsmanager"
    {{- end }}
    {{- end }}
{{- end }}
